version: '3.7'

services:

  bot:
    build: bot
    env_file:
      - .env

  postgresql:
    image: postgres:17.2
    ports:
      - "5432:5432"
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:4.0.4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  worker:
    build: worker
    env_file:
      - .env

  api:
    build: api
    ports:
      - "8000:8000"
      - "80:80"
    env_file:
      - .env
